# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MyAlamofire' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyAlamofire
  pod 'Alamofire', '~> 4.0'

  target 'MyAlamofireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyAlamofireUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
