# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'KingfisherApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KingfisherApp
  pod 'Kingfisher'
  pod 'FLEX', '~> 2.0', :configurations => ['Debug']

  target 'KingfisherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KingfisherAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
