# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SnapKitApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 3.0.2'

  # Pods for SnapKitApp

  target 'SnapKitAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SnapKitAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
